### ISSUE TITLE
SQL Structure?

### ISSUE THREAD

**Issue by Maeggi** [jlekowski/battleships#1]
Hello, what is the MYSQL Structure?
MYSQL not working, can u help?
Thanks

**Comment by jlekowski** [comment]
@Maeggi, it is a legacy project and I do not recommend to use it any more. It creates tables in **sqlite** if not present already, as you can find in https://github.com/jlekowski/battleships/blob/9fedb94d3990ea7bd3308a56ba31b6894f5341b2/lib/Battleships/Game/Manager.php#L95.

The code was split into [API](https://github.com/jlekowski/battleships-api) and [Web Client](https://github.com/jlekowski/battleships-webclient) and refactored. I suggest that you give these a go, as they are being supported and of much better quality.

You can find demos here http://dev.lekowski.pl/. Thank you for your interest.

**Comment by Maeggi** [comment]
Hi jlekowski, i like the game. then i upgrade this version to mysqli and php7. its thats ok for u? sry, for my english, germany :D

**Comment by jlekowski** [comment]
@Maeggi, I wouldn't consider changing `PDO` to `mysqli` an upgrade. Of course you are free to fork the repository and change whatever you wish.
I do not plan to add any changes here. The code reflects my coding skills a few years ago, is not a good example to learn from, and far from modern PHP development. Yet, I hope you will enjoy altering it to your needs.
